[project]
name = "django-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "django-taggit>=6.1.0",
    "markdown>=3.10",
    "python-decouple>=3.8",
]
